//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp.DataLayers.SqlServer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DemoApp.DataLayers.SqlServer.CommandList", typeof(CommandList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_BoPhan_Get.
        /// </summary>
        internal static string BoPhan_Get {
            get {
                return ResourceManager.GetString("BoPhan_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_BoPhan_SelectWithNhanVienCount.
        /// </summary>
        internal static string BoPhan_SelectWithNhanVienCount {
            get {
                return ResourceManager.GetString("BoPhan_SelectWithNhanVienCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_CaLam_Delete.
        /// </summary>
        internal static string CaLam_Delete {
            get {
                return ResourceManager.GetString("CaLam_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_CaLam_Insert.
        /// </summary>
        internal static string CaLam_Insert {
            get {
                return ResourceManager.GetString("CaLam_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_CaLam_List.
        /// </summary>
        internal static string CaLam_Select {
            get {
                return ResourceManager.GetString("CaLam_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_CaLam_SelectByMaNV.
        /// </summary>
        internal static string CaLam_SelectByMaNV {
            get {
                return ResourceManager.GetString("CaLam_SelectByMaNV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_CaLam_Update.
        /// </summary>
        internal static string CaLam_Update {
            get {
                return ResourceManager.GetString("CaLam_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_ChamCong_Delete.
        /// </summary>
        internal static string ChamCong_Delete {
            get {
                return ResourceManager.GetString("ChamCong_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_ChamCong_Insert.
        /// </summary>
        internal static string ChamCong_Insert {
            get {
                return ResourceManager.GetString("ChamCong_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_ChamCong_KiemTraDaChamCong.
        /// </summary>
        internal static string ChamCong_KiemTraDaChamCong {
            get {
                return ResourceManager.GetString("ChamCong_KiemTraDaChamCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_ChamCong_List.
        /// </summary>
        internal static string ChamCong_Select {
            get {
                return ResourceManager.GetString("ChamCong_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_ChamCong_SelectByMaNV.
        /// </summary>
        internal static string ChamCong_SelectByMaNV {
            get {
                return ResourceManager.GetString("ChamCong_SelectByMaNV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_ChamCong_TongHopChamCong.
        /// </summary>
        internal static string ChamCong_TongHopChamCong {
            get {
                return ResourceManager.GetString("ChamCong_TongHopChamCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_ChamCong_TongHopChamCongTheoThang.
        /// </summary>
        internal static string ChamCong_TongHopChamCongTheoThang {
            get {
                return ResourceManager.GetString("ChamCong_TongHopChamCongTheoThang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_ChamCong_Update.
        /// </summary>
        internal static string ChamCong_Update {
            get {
                return ResourceManager.GetString("ChamCong_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_ChamCong_UpdateThoiGianKetThucChamCong.
        /// </summary>
        internal static string ChamCong_UpdateThoiGianKetThucChamCong {
            get {
                return ResourceManager.GetString("ChamCong_UpdateThoiGianKetThucChamCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_ChucVu_Insert.
        /// </summary>
        internal static string ChucVu_Create {
            get {
                return ResourceManager.GetString("ChucVu_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_ChucVu_Delete.
        /// </summary>
        internal static string ChucVu_Delete {
            get {
                return ResourceManager.GetString("ChucVu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_ChucVu_Select.
        /// </summary>
        internal static string ChucVu_Select {
            get {
                return ResourceManager.GetString("ChucVu_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_ChucVu_Update.
        /// </summary>
        internal static string ChucVu_Update {
            get {
                return ResourceManager.GetString("ChucVu_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_FileHopDong_Delete.
        /// </summary>
        internal static string FileHopDong_Delete {
            get {
                return ResourceManager.GetString("FileHopDong_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_FileHopDong_GetByMaHD.
        /// </summary>
        internal static string FileHopDong_GetByMaHD {
            get {
                return ResourceManager.GetString("FileHopDong_GetByMaHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_FileHopDong_GetFileById.
        /// </summary>
        internal static string FileHopDong_GetFileById {
            get {
                return ResourceManager.GetString("FileHopDong_GetFileById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_FileHopDong_Insert.
        /// </summary>
        internal static string FileHopDong_Insert {
            get {
                return ResourceManager.GetString("FileHopDong_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_FileHopDong_Select.
        /// </summary>
        internal static string FileHopDong_Select {
            get {
                return ResourceManager.GetString("FileHopDong_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_HopDong_GetByMaHD.
        /// </summary>
        internal static string HopDong_GetByMaHD {
            get {
                return ResourceManager.GetString("HopDong_GetByMaHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_HopDong_Delete.
        /// </summary>
        internal static string HopDongLaoDong_Delete {
            get {
                return ResourceManager.GetString("HopDongLaoDong_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_HopDong_GetByMaHD.
        /// </summary>
        internal static string HopDongLaoDong_GetByMaHD {
            get {
                return ResourceManager.GetString("HopDongLaoDong_GetByMaHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_HopDong_GetByMaNV.
        /// </summary>
        internal static string HopDongLaoDong_GetByMaNV {
            get {
                return ResourceManager.GetString("HopDongLaoDong_GetByMaNV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_HopDong_Insert.
        /// </summary>
        internal static string HopDongLaoDong_Insert {
            get {
                return ResourceManager.GetString("HopDongLaoDong_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_HopDong_Select.
        /// </summary>
        internal static string HopDongLaoDong_Select {
            get {
                return ResourceManager.GetString("HopDongLaoDong_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_HopDong_Update.
        /// </summary>
        internal static string HopDongLaoDong_Update {
            get {
                return ResourceManager.GetString("HopDongLaoDong_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_LoaiCaLam_List.
        /// </summary>
        internal static string LoaiCaLam_Select {
            get {
                return ResourceManager.GetString("LoaiCaLam_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_LoaiHopDong_Select.
        /// </summary>
        internal static string LoaiHopDong_Select {
            get {
                return ResourceManager.GetString("LoaiHopDong_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_LoaiNghiPhep_List.
        /// </summary>
        internal static string LoaiNghiPhep_List {
            get {
                return ResourceManager.GetString("LoaiNghiPhep_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_NghiPhep_Delete.
        /// </summary>
        internal static string NghiPhep_Delete {
            get {
                return ResourceManager.GetString("NghiPhep_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_NghiPhep_Insert.
        /// </summary>
        internal static string NghiPhep_Insert {
            get {
                return ResourceManager.GetString("NghiPhep_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_NghiPhep_List.
        /// </summary>
        internal static string NghiPhep_List {
            get {
                return ResourceManager.GetString("NghiPhep_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_NghiPhep_ListByMaNV.
        /// </summary>
        internal static string NghiPhep_ListByMaNV {
            get {
                return ResourceManager.GetString("NghiPhep_ListByMaNV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_NghiPhep_Update.
        /// </summary>
        internal static string NghiPhep_Update {
            get {
                return ResourceManager.GetString("NghiPhep_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_NghiPhep_UpdateTrangThai.
        /// </summary>
        internal static string NghiPhep_UpdateTrangThai {
            get {
                return ResourceManager.GetString("NghiPhep_UpdateTrangThai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_NhanVien_CountByGender.
        /// </summary>
        internal static string NhanVien_CountByGender {
            get {
                return ResourceManager.GetString("NhanVien_CountByGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_NhanVien_Delete.
        /// </summary>
        internal static string NhanVien_Delete {
            get {
                return ResourceManager.GetString("NhanVien_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_NhanVien_Detail.
        /// </summary>
        internal static string NhanVien_Detail {
            get {
                return ResourceManager.GetString("NhanVien_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_NhanVien_Insert.
        /// </summary>
        internal static string NhanVien_Insert {
            get {
                return ResourceManager.GetString("NhanVien_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_NhanVien_ListPaged.
        /// </summary>
        internal static string NhanVien_ListPaged {
            get {
                return ResourceManager.GetString("NhanVien_ListPaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_NhanVien_SearchAndFilterPaged.
        /// </summary>
        internal static string NhanVien_SearchAndFilterPaged {
            get {
                return ResourceManager.GetString("NhanVien_SearchAndFilterPaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_NhanVien_Select.
        /// </summary>
        internal static string NhanVien_Select {
            get {
                return ResourceManager.GetString("NhanVien_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_NhanVien_Update.
        /// </summary>
        internal static string NhanVien_Update {
            get {
                return ResourceManager.GetString("NhanVien_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_PhongBan_Delete.
        /// </summary>
        internal static string PhongBan_Delete {
            get {
                return ResourceManager.GetString("PhongBan_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_PhongBan_Get.
        /// </summary>
        internal static string PhongBan_Get {
            get {
                return ResourceManager.GetString("PhongBan_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_PhongBan_Insert.
        /// </summary>
        internal static string PhongBan_Insert {
            get {
                return ResourceManager.GetString("PhongBan_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_PhongBan_SearchAndFilterPaged.
        /// </summary>
        internal static string PhongBan_SearchAndFilterPaged {
            get {
                return ResourceManager.GetString("PhongBan_SearchAndFilterPaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_PhongBan_SearchByName.
        /// </summary>
        internal static string PhongBan_SearchByName {
            get {
                return ResourceManager.GetString("PhongBan_SearchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_PhongBan_Select.
        /// </summary>
        internal static string PhongBan_Select {
            get {
                return ResourceManager.GetString("PhongBan_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_PhongBan_SelectByParent.
        /// </summary>
        internal static string PhongBan_SelectByParent {
            get {
                return ResourceManager.GetString("PhongBan_SelectByParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_PhongBan_SelectPaged.
        /// </summary>
        internal static string PhongBan_SelectedPaged {
            get {
                return ResourceManager.GetString("PhongBan_SelectedPaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_PhongBan_Update.
        /// </summary>
        internal static string PhongBan_Update {
            get {
                return ResourceManager.GetString("PhongBan_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_QuaTrinh_Insert.
        /// </summary>
        internal static string QuaTrinh_Create {
            get {
                return ResourceManager.GetString("QuaTrinh_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_QuaTrinh_Delete.
        /// </summary>
        internal static string QuaTrinh_Delete {
            get {
                return ResourceManager.GetString("QuaTrinh_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_QuaTrinh_GetByMaNV.
        /// </summary>
        internal static string QuaTrinh_GetByMaNV {
            get {
                return ResourceManager.GetString("QuaTrinh_GetByMaNV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_QuaTrinh_Update.
        /// </summary>
        internal static string QuaTrinh_Update {
            get {
                return ResourceManager.GetString("QuaTrinh_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_TaiKhoan_DeleteByMaNV.
        /// </summary>
        internal static string TaiKhoan_Delete {
            get {
                return ResourceManager.GetString("TaiKhoan_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_TaiKhoan_SelectAll.
        /// </summary>
        internal static string TaiKhoan_SelectAll {
            get {
                return ResourceManager.GetString("TaiKhoan_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_TaiKhoan_Update.
        /// </summary>
        internal static string TaiKhoan_Update {
            get {
                return ResourceManager.GetString("TaiKhoan_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_TaiKhoan_UpdateRoleByMaNV.
        /// </summary>
        internal static string TaiKhoan_UpdateRoleByMaNV {
            get {
                return ResourceManager.GetString("TaiKhoan_UpdateRoleByMaNV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proc_ViTri_Select.
        /// </summary>
        internal static string ViTri_Select {
            get {
                return ResourceManager.GetString("ViTri_Select", resourceCulture);
            }
        }
    }
}
